version: '2.4'

services:

  server:
    build:
      context: ../../
    extends:
      file: ../../${CORERELDIR}infra/compose/base.yml
      service: server

  idilic:
    build:
      context: ../../
    extends:
      file: ../../${CORERELDIR}infra/compose/base.yml
      service: idilic

  database:
    extends:
      file: ../../vendor/seanmorris/ids/infra/compose/base.yml
      service: database

  kafka:
    volumes: ['firehose:/bitnami/kafka']
    image: 'bitnami/kafka:latest'

  zookeeper:
    image: 'bitnami/zookeeper:latest'

volumes:
  firehose:
    driver: local
  schema:
    driver: local
