version: '2.4'

services:

  centralconsumer:
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: centralconsumer

  idilic:
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: idilic

  server:
    ports: ['${IDS_EXPOSE_HTTP}:80']
    depends_on: [database]
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: server

  database:
    ports: ['${IDS_EXPOSE_SQL}:${IDS_DATABASES_MAIN_PORT}']
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: database

  kafka:
    extends:
      file: base.yml
      service: kafka
    depends_on:
      - zookeeper

  zookeeper:
    extends:
      file: base.yml
      service: zookeeper

volumes:
  zoo:
    driver: local
  firehose:
    driver: local
  schema:
    driver: local
