version: '2.4'

services:

  centralconsumer:
    depends_on: [database]
    volumes: ['${OUTROOTDIR}:/app', "/tmp:/tmp"]
    extends:
      file: base.yml
      service: centralconsumer

  kayveeproducer:
    depends_on: [database]
    volumes: ['${OUTROOTDIR}:/app', "/tmp:/tmp"]
    extends:
      file: base.yml
      service: kayveeproducer

  idilic:
    depends_on: [database]
    volumes: ['${OUTROOTDIR}:/app']
    extends:
      file: base.yml
      service: idilic

  server:
    volumes: ['${OUTROOTDIR}:/app']
    ports: ['${IDS_EXPOSE_HTTP-0}:8080']
    build:
      context: ../../
    extends:
      file: base.yml
      service: server

  database:
    ports: ['${IDS_EXPOSE_SQL-0}:${IDS_DATABASES_MAIN_PORT}']
    extends:
      file: base.yml
      service: database

  kafka:
    extends:
      file: base.yml
      service: kafka
    depends_on:
      - zookeeper

  zookeeper:
    extends:
      file: base.yml
      service: zookeeper

  brunch:
    extends:
      file: base.yml
      service: brunch

volumes:
  zoo:
    driver: local
  firehose:
    driver: local
  schema:
    driver: local
